baseURL: "https://Adrian13985.github.io/"
title: "Adrian的个人博客"
pagination:
  pagerSize: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false

# 启用数学公式 (KaTeX) 和 代码高亮
markup:
  highlight:
    noClasses: false
    style: monokai # 极其适合代码展示
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true # 允许在 Markdown 中嵌入 HTML (如 iframe 视频)

params:
  env: production
  description: "Embedded Systems, FPGA, Linux Kernel & Philosophy."
  author: "Adrian"
  # 界面设置
  defaultTheme: auto # 跟随系统深色模式
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true # 代码块右上角显示复制按钮
  
  # 启用 LaTeX 数学公式支持
  math: true 
  
  # 首页配置
  homeInfoParams:
    Title: "Hello, World."
    Content: >
      微电子 | 嵌入式 Linux | FPGA | 篮球 
      
      
  
  socialIcons:
    - name: github
      url: "https://github.com/Adrian13985"
    - name: email
      url: "mailto:frankadrian985@gmail.com"

menu:
  main:
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 10
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 20
    - identifier: search
      name: 搜索
      url: /search/
      weight: 30
[outputs]
  home = ["HTML", "RSS", "JSON"]
